// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WenNtoM.Models;

public partial class Interessen
{
    public int InteressenId { get; set; }

    public string Interessen1 { get; set; }

    public virtual ICollection<PerInt> PerInt { get; set; } = new List<PerInt>();
}