// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WenNtoM.Models;

public partial class PerInt
{
    public int PerFk { get; set; }

    public int IntFk { get; set; }

    public virtual Interessen IntFkNavigation { get; set; }

    public virtual Personen PerFkNavigation { get; set; }
}