// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdressWeb.Models;

public partial class Adressen
{
    public int AdrId { get; set; }

    public string Name { get; set; }

    public string Adresse { get; set; }

    public string Telefon { get; set; }

    public int PlzFk { get; set; }

    public virtual Postleitzahlen PlzFkNavigation { get; set; }
}