// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AdressWeb.Models;

public partial class CS2023KursContext : DbContext
{
    public CS2023KursContext()
    {
    }

    public CS2023KursContext(DbContextOptions<CS2023KursContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Adressen> Adressen { get; set; }

    public virtual DbSet<Postleitzahlen> Postleitzahlen { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-0O4SDSG\\SQLEXPRESS;Initial Catalog=CS2023Kurs;Integrated Security=True; Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Adressen>(entity =>
        {
            entity.HasKey(e => e.AdrId).HasName("PK_Adresse");

            entity.Property(e => e.AdrId).HasColumnName("AdrID");
            entity.Property(e => e.Adresse)
                .IsRequired()
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.PlzFk).HasColumnName("PlzFK");
            entity.Property(e => e.Telefon)
                .IsRequired()
                .HasMaxLength(25)
                .IsFixedLength();

            entity.HasOne(d => d.PlzFkNavigation).WithMany(p => p.Adressen)
                .HasForeignKey(d => d.PlzFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Adressen_Postleitzahlen");
        });

        modelBuilder.Entity<Postleitzahlen>(entity =>
        {
            entity.HasKey(e => e.PlzId);

            entity.Property(e => e.PlzId).HasColumnName("PlzID");
            entity.Property(e => e.Ort)
                .IsRequired()
                .HasMaxLength(100)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}